name: Build
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    strategy:
      fail-fast: false
      matrix:
        board:
          - nice_nano
          - nice_nano_v2
        shield:
          - choc_ergo_left
          - choc_ergo_right
          - hypergolic_left
          - hypergolic_right
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            bootloader/
            modules/
            tools/
            zephyr/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: Initialize workspace (west init)
        run: west init -l config
      - name: Update modules (west update)
        run: west update
      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: Prepare variables
        id: variables
        run: |
          if [ -n "${{ matrix.shield }}" ]; then
            SHIELD_ARG="-DSHIELD=${{ matrix.shield }}"
            FILE_NAME="${{ matrix.shield }}".uf2
            ARTIFACT_NAME="$(echo ${{ matrix.shield }} | perl -pe 's/_left|_right//g')-${{ matrix.board }}"
          else
            FILE_NAME="${{ matrix.board }}".uf2
            SHIELD_ARG=
            ARTIFACT_NAME="${{ matrix.board }}"
          fi

          echo ::set-output name=shield-arg::${SHIELD_ARG}
          echo ::set-output name=file-name::${FILE_NAME}
          echo ::set-output name=artifact-name::${ARTIFACT_NAME}
      - name: Build (west build)
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- ${{ steps.variables.outputs.shield-arg }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          mv build/zephyr/zmk.uf2 ${{ steps.variables.outputs.file-name }}
      - name: Generated DTS file
        if: always()
        run: cat -n build/zephyr/${{ matrix.board }}.dts.pre.tmp
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.variables.outputs.artifact-name }}
          path: '*.uf2'
        continue-on-error: true
